spring:
  application:
    name: payments
  datasource:
    jdbcUrl: ${JDBC_URL}
    username: ${JDBC_USER}
    password: ${JDBC_PASSWORD}
    # driverClassName: org.postgresql.Driver
  flyway: 
    baseline-on-migrate: true
server:
  port: ${PORT:8080}
  servlet:
    context-path: /payments/v1