spring:
  application:
    name: payments
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/payments-challenge
    username: postgres
    password: root
    # driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        # The SQL dialect makes Hibernate generate better SQL for the chosen database
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: none
server:
  port: 8080
  servlet:
    context-path: /payments/v1