spring:
  application:
    name: payments
  datasource:
    driverClassName: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://localhost:5432/payments-challenge
    username: postgres
    password: docker
server:
  host: http://localhost
  port: 8080
  servlet:
    context-path: /payments/v1