spring:
  application:
    name: payments
  datasource:
    jdbcUrl: ${JDBC_URL}
    username: ${JDBC_USER}
    password: ${JDBC_PASSWORD}
    # driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        # The SQL dialect makes Hibernate generate better SQL for the chosen database
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: none
server:
  port: ${PORT:8080}
  servlet:
    context-path: /payments/v1